### ISSUE TITLE
missing documentation tracking issue 

### ISSUE THREAD

**Issue by jd-lara** [NREL-SIIP/PowerSimulationsDynamics.jl#233]
- [ ] Recently added models 
- [ ] Load Models and IM 
- [ ] Add Model Developer Section to docs 
- [ ] Add testing guidelines for new models
